### ISSUE TITLE
Add Z offset for waypoints

### ISSUE THREAD

**Issue by gtbikev** [gtbikev/route-builder#7]
From my experience, the map builder outputs translate to waypoints that are half-buried, and in some cases (especially hilly terrain), they would be low enough to not be able to place, leading to total navigation failures. I found that adding a flat positive offset to all Z coordinates, usually +8 to +10, was useful in fixing that issue - probably best for it to be configurable.

Just a flat offset. Without it, direct implementation of the coordinates from map builder has the waypoints half buried, but a flat offset (I've found +8 to +10 to consistently give good results) lifts them up off the ground to float like normal. Usually it's only a cosmetic difference, but sometimes having them buried will give the navigator fits :)
But yeah, it's really just z = z+x, where X is either a flat offset or (probably better) a user configured constant offset value with some reasonable default like 8.

**Comment by Frank-Fox** [comment]
> 
> 
> From my experience, the map builder outputs translate to waypoints that are half-buried, and in some cases (especially hilly terrain), they would be low enough to not be able to place, leading to total navigation failures. I found that adding a flat positive offset to all Z coordinates, usually +8 to +10, was useful in fixing that issue - probably best for it to be configurable.
> 
> Just a flat offset. Without it, direct implementation of the coordinates from map builder has the waypoints half buried, but a flat offset (I've found +8 to +10 to consistently give good results) lifts them up off the ground to float like normal. Usually it's only a cosmetic difference, but sometimes having them buried will give the navigator fits :)
> But yeah, it's really just z = z+x, where X is either a flat offset or (probably better) a user configured constant offset value with some reasonable default like 8.
In my case, I prefer to completely bury the WayPointLists giving it a "Z" -10 with respect to the original value. In this way, I get the markers not to be seen on the ground (personally it bothers me) I only tried it on flat terrain and it works very good.

There is no point in seeing it on the ground, since you can see it in the MAP but it is only a thought :)

Example: "Z": 58.05 Change "Z": 48.05

**Comment by ghost** [comment]
In my case, I prefer to completely bury the WayPointLists giving it a "Z" -10 with respect to the original value. In this way, I get the markers not to be seen on the ground (personally it bothers me) I only tried it on flat terrain and it works very good.

There is no point in seeing it on the ground, since you can see it in the MAP but it is only a thought :)
Example: "Z": 58.05 Change "Z": 48.05

**Comment by gtbikev** [comment]
Fair point. As originally requested, the implementation will be done with a configurable field allowing users to specify positive/negative Z offset values.

This implementation will focus on applying Z offset values to all waypoints. There is another enhancement request to adjust waypoints individually: https://github.com/gtbikev/route-builder/issues/14

**Comment by ghost** [comment]
those are good news :) waiting for the update...

**Comment by murech** [comment]
Implemented. This feature will be merged to master once other milestone features have been implemented due to dependencies and testing.
